# Worker/Executor PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.PVCName}}
  namespace: {{ .Namespace }}
  labels:
    app: funnel
    taskId: {{.TaskId}}
spec:
  {{- if .StorageClassName }}
  storageClassName: {{.StorageClassName}} # PVCMode "pvc": dynamic provisioning
  {{- else }}
  storageClassName: "" # Required for static provisioning
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{if ne .DiskGb 0.0}}"{{printf "%.0fGi" .DiskGb}}"{{else}}"1Gi"{{end}}
  {{- if not .StorageClassName }}
  volumeName: funnel-worker-pv-{{.TaskId}}
  {{- end }}
