apiVersion: batch/v1
kind: Job
metadata:
  ## DO NOT CHANGE NAME
  name: {{.TaskId}}
  namespace: {{.Namespace}}
spec: 
  backoffLimit: 0
  completions: 1
  template:
    spec:
      containers: 
        - name: {{printf "funnel-worker-%s" .TaskId}}
          image: ohsucompbio/funnel-kubernetes-worker:latest
          imagePullPolicy: IfNotPresent
          args:
            - 'funnel'
            - 'worker'
            - 'run'
            - '--EventWriters'
            - 'log'
            - '--EventWriters'
            - 'rpc'
            - '--Server.Hostname'
            - 'localhost'
            - '--Server.RPCPort'
            - '9090'
            - '--taskID'
            - {{.TaskId}}
          resources:
              requests:
                cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
                memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
          volumeMounts:
            - name: {{printf "funnel-storage-%s" .TaskId}}
              mountPath: {{printf "/opt/funnel/funnel-work-dir/%s" .TaskId}}
          securityContext:
            privileged: true

      restartPolicy: Never
      volumes: 
        - name: {{printf "funnel-storage-%s" .TaskId}}
          emptyDir: {}
