apiVersion: batch/v1
kind: Job
metadata:
  ## DO NOT CHANGE NAME
  name: {{.TaskId}}
  namespace: {{.Namespace}}
spec: 
  backoffLimit: 0
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers: 
        - name: {{printf "funnel-worker-%s" .TaskId}}
          image: ohsucompbio/funnel-kubernetes-worker:latest
          imagePullPolicy: IfNotPresent
          args:
            - "funnel"
            - "worker"
            - "run"
            - "--EventWriters"
            - "log"
            - "--EventWriters"
            - "rpc"
            ## YOU MUST SET THE SERVER HOSTNAME
            - "--Server.Hostname"
            - "0.0.0.0"
            - "--Server.RPCPort"
            - "9090"
            - "--taskID"
            - {{.TaskId}}
            - "--RPCClient.MaxRetries"
            - "3"
            - "--RPCClient.Timeout "
            - "10s"
          resources:
              requests:
                cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
                memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
          volumeMounts:
            - name: {{printf "funnel-storage-%s" .TaskId}}
              mountPath: {{printf "/opt/funnel/funnel-work-dir/%s" .TaskId}}
          securityContext:
            privileged: true

      volumes: 
        - name: {{printf "funnel-storage-%s" .TaskId}}
          emptyDir: {}
